---
- name: K3s cluster - prepare vms
  hosts: all
  become: yes
  vars_files:
    - global-vars.yaml
    - roles-vars.yaml
  roles:
    - role: ../../../../ansible/roles/populate-hosts-with-inventory
    - role: ../../../../ansible/roles/contrib-non-free-repos
    - role: ../../../../ansible/roles/sudo-passwordless
    - role: ../../../../ansible/roles/base-packages

