---
- name: Add all hosts to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_host'] }} {{item}}"
    state: present
  with_items: "{{ groups['all'] }}"

- name: Add all hosts to /etc/cloud/templates/hosts.debian.tmpl used to generate /etc/hosts file after reboots
  lineinfile:
    dest: /etc/cloud/templates/hosts.debian.tmpl
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_host'] }} {{item}}"
    state: present
  with_items: "{{ groups['all'] }}"
